use_frameworks!
source 'https://github.com/Artsy/Specs.git'
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, "8.0"


target  "地图" do
   
pod 'AMap2DMap', '~> 4.0.0'
 pod 'AMapSearch', '~> 4.1.0'

end

